/* Generated By:JJTree&JavaCC: Do not edit this line. OverviewParserConstants.java */
package overview.ovi.compiler;

public interface OverviewParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int ENTITY = 13;
  int IS = 14;
  int ON = 15;
  int PARAMETER = 16;
  int BY = 17;
  int UNIQUE = 18;
  int CONTAINS = 19;
  int WATCH = 20;
  int WHEN = 21;
  int START = 22;
  int FINISH = 23;
  int SEND = 24;
  int THIS = 25;
  int EXCEPTION = 26;
  int INTEGER_LITERAL = 27;
  int DECIMAL_LITERAL = 28;
  int HEX_LITERAL = 29;
  int OCTAL_LITERAL = 30;
  int FLOATING_POINT_LITERAL = 31;
  int EXPONENT = 32;
  int CHARACTER_LITERAL = 33;
  int STRING_LITERAL = 34;
  int IDENTIFIER = 35;
  int LETTER = 36;
  int DIGIT = 37;
  int LPAREN = 38;
  int RPAREN = 39;
  int LBRACE = 40;
  int RBRACE = 41;
  int LBRACKET = 42;
  int RBRACKET = 43;
  int SEMICOLON = 44;
  int COMMA = 45;
  int DOT = 46;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"entity\"",
    "\"is\"",
    "\"on\"",
    "\"parameter\"",
    "\"by\"",
    "\"unique\"",
    "\"contains\"",
    "\"watch\"",
    "\"when\"",
    "\"start\"",
    "\"finish\"",
    "\"->\"",
    "\"this\"",
    "\"exception\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
  };

}
