/* Generated By:JJTree: Do not edit this line. OverviewParserTreeConstants.java */

package overview.ovi.compiler;

public interface OverviewParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTENTITYDECLARATION = 1;
  public int JJTENTITYBODY = 2;
  public int JJTWATCHDECLARATION = 3;
  public int JJTWHENDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTPARAMETER = 6;
  public int JJTNAME = 7;
  public int JJTEVENTDECLARATION = 8;
  public int JJTVALUE = 9;
  public int JJTVALUEPART = 10;
  public int JJTLITERAL = 11;
  public int JJTSTRINGLITERAL = 12;
  public int JJTCHARACTERLITERAL = 13;
  public int JJTFLOATINGPOINTLITERAL = 14;
  public int JJTINTEGERLITERAL = 15;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "EntityDeclaration",
    "EntityBody",
    "WatchDeclaration",
    "WhenDeclaration",
    "MethodDeclaration",
    "Parameter",
    "Name",
    "EventDeclaration",
    "Value",
    "ValuePart",
    "Literal",
    "StringLiteral",
    "CharacterLiteral",
    "FloatingPointLiteral",
    "IntegerLiteral",
  };
}
